tables_test_task/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('index/', views.home, name="index"),
    path('create_post/', views.createPost),
    path('post/<slug:slug>/', views.post, name="post")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=200)
    profile_pic = models.ImageField(
        null=True, blank=True, upload_to="images/", default="/user.png")
    bio = models.TextField(null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        name = str(self.first_name)
        if self.last_name:
            name += ' ' + str(self.last_name)
        return name


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(
        null=True, blank=True, upload_to="images", default="images/placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)


class PostComment(models.Model):
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.body

    @property
    def created_dynamic(self):
        now = timezone.now()
        return now

base/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

base/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from .models import *
from .decorator import admin_only


def home(request):
    posts = Post.objects.filter(active=True, featured=True)

    context = {'posts': posts}
    return render(request, 'index.html', context)


@admin_only
@login_required(login_url="home")
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('index')

    context = {'form': form}
    return render(request, 'post_form.html', context)


def post(request, slug):
    try:
        post = Post.objects.get(slug=slug)
    except:
        return HttpResponse('This post doesnt exist')
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        PostComment.objects.create(
            author=request.user.profile,
            post=post,
            body=request.POST['comment']
        )
        messages.success(request, "You're comment was successfuly posted!")

        return redirect('post', slug=post.slug)

    context = {'post': post}
    return render(request, 'post.html', context)

templates/index.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Xeyyam Sharif</title>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        } -
        gtag('js', new Date());

        gtag('config', 'UA-47692315-56');
    </script>


    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
    <link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>

<body>

    <section class="s1">
        <div class="main-container">
            <div class="greeting-wrapper">
                <h1>Hi, I'm Xeyyam Sharif</h1>
            </div>


            <div class="intro-wrapper">
                <div class="left-column">
                    <img id="profile_pic" src="{% static 'images/images/portfolio.jpg' %}">
                    <h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

                    <div id="theme-options-wrapper">
                        <div data-mode="light" id="light-mode" class="theme-dot"></div>
                        <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
                        <div data-mode="green" id="green-mode" class="theme-dot"></div>
                        <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
                    </div>

                    <p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
                </div>

                <div class="right-column">

                    <div id="preview-shadow">
                        <div id="preview">
                            <div id="corner-tl" class="corner"></div>
                            <div id="corner-tr" class="corner"></div>
                            <h3>What I Do</h3>
                            <p>I am developing web apps with django and django restframework</p>
                            <div id="corner-br" class="corner"></div>
                            <div id="corner-bl" class="corner"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="s2">
        <div class="main-container">

            <div class="about-wrapper">
                <div class="about-me">
                    <h4>More about me</h4>

                    <p>I build new projects just to tickle my brain</p>

                    <p>I am ambitious to software and tech</p>


                    <hr>

                    <h4>TOP EXPERTISE</h4>

                    <p>Developer with primary focus on Django : <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a></p>

                    <div id="skills">
                        <ul>
                            <li>Python</li>
                            <li>Django</li>
                            <li>JavaScript</li>
                            <li>Postgres</li>
                        </ul>

                        <ul>
                            <li>Django Rest framework</li>
                            <li>Docker</li>

                            <li>HTML/CSS</li>
                        </ul>

                    </div>

                </div>


                <div class="social-links">
                    <img id="social_img" src="{% static 'images/follow.jpg' %}">
                    <h3>Find me on Twitter, Instagram</h3>

                    <a target="_blank" href="https://www.instagram.com/sherifzad/">instagram: @sherifzad</a>
                    <br>
                    <a target="_blank" href="https://twitter.com/SherifXeyyam">Twitter: @SherifXeyyam</a>
                </div>
            </div>

        </div>
    </section>

    <section class="s1">
        <div class="main-container">
            <h3 style="text-align: center;">Some of my past projects</h3>
            <div class="post-wrapper">
                {% for post in posts %}
                <div>
                    <div class="post">
                        <img class="thumbnail" src="{{post.thumbnail.url}}">
                        <div class="post-preview">
                            <h6 class="post-title">{{post.headline}}</h6>
                            <p class="post-intro">{{post.sub_headline}}</p>
                            <a href="{%  url 'post' post.slug %}">Read More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>


    <script type="text/javascript">
        let static = "{% static 'css' %}"
    </script>

    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/main.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Xeyyam Sherif</title>

    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-47692315-56');
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
</head>

<body>


    {% block content %}
    <!-- Content goes here -->
    {% endblock content %}

</body>

</html>

templates/post.html
{% extends 'main.html' %} {% load static %} {% block content %}

<style type="text/css">
    img {
        max-width: 100%;
        object-fit: cover;
    }
    
    .featured_image {
        margin-top: 20px;
        margin-bottom: 20px;
    }
    
    .post-container {
        width: 900px;
        margin: 0 auto;
        padding-top: 20px;
        padding-bottom: 20px;
    }
    
    .comments-wrapper {
        margin-top: 50px;
        padding: 10px;
        border: 1px solid var(--borderColor);
        -webkit-box-shadow: -1px 1px 3px -1px rgba(0, 0, 0, 0.75);
        -moz-box-shadow: -1px 1px 3px -1px rgba(0, 0, 0, 0.75);
        box-shadow: -1px 1px 3px -1px rgba(0, 0, 0, 0.75);
    }
    
    .comment {
        display: flex;
        padding: 15px;
    }
    
    .comment-author {
        font-size: 14px;
        font-weight: 700;
        color: rgb(30, 174, 219) !important;
        margin: 2px;
    }
    
    .author-pic {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        margin-right: 10px;
    }
    
    .comment-body {
        font-size: 14px;
    }
    
    @media screen and (max-width: 900px) {
        .post-container {
            width: 95%;
        }
    }
</style>

<div class="post-container">


    <img class="featured_image" src="{{post.thumbnail.url}}"> {% for tag in post.tags.all %}
    <span class="tag">{{tag}}</span> {% endfor %}
    <hr>

    <h1>{{post.headline}}</h1>
    <h4>{{post.sub_headline}}</h4>
    <br>

    <p>{{post.body|safe}}</p>

    <div class="comments-wrapper">
        <h5>Comments: {{post.postcomment_set.all.count}}</h5>
        <hr>
        <!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username 
		-->
        {% if request.user.is_authenticated %}
        <form action="" method="POST">
            {% csrf_token %}
            <textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
            <br>
            <input class="btn btn-info" type="submit" value="Submit">
        </form>
        {% else %}
        <p>Create an account to comment:</p>
        <a class="btn btn-primary" href="{% url 'register' %}">Register/Login</a> {% endif %}

        <hr> {% for comment in post.postcomment_set.all %}
        <div class="comment">
            <img class="author-pic" src="{{comment.author.profile_pic.url}}">
            <div>
                <p class="comment-author">{{comment.author}}: {{comment.created|date:"M-d-Y"}}</p>
                <p class="comment-body">{{comment.body}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/post_form.html
{% extends 'main.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}

<style type="text/css">
    #div_id_tags>div {
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }
</style>
<div class="main-container">

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{form.media}} {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Submit Post">

    </form>
</div>

{% endblock content %}